### ISSUE TITLE
fix: Update keywords on docs pages

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#223] opened 2023-12-06 16:59 UTC
## Current

Right now, there's not been consistency on keywords. Keywords are a way to improve the SEO of the pages. We should do a review of each page to determine if we could be doing a better job.

ref: https://github.com/open-sauced/docs/pull/213#discussion_r1415289023

## Solution

Go through the pages most likely to be viewed by someone looking for answers about open source. Update the keywords to showcase the resource.

For example, the maintainers guide might look like this:

```
keywords:
  - "open source maintainers guide" 
  - "open source maintainer"
  - "open-source project management"
  - "community management in open-source" 
 ```

**Comment by Suraj-kumar00** [comment] 2024-01-11 18:43
Hi @BekahHW, how are you doing? Can I work on this issue if you could assign it to me? Also, may I ask for help if I get stuck?

**Comment by BekahHW** [comment] 2024-01-11 20:08
@Suraj-kumar00 sure. Just read our [Contributing docs](https://docs.opensauced.pizza/contributing/introduction-to-contributing/) to learn how to assign yourself

**Comment by Suraj-kumar00** [comment] 2024-01-12 05:34
> @Suraj-kumar00 sure. Just read our [Contributing docs](https://docs.opensauced.pizza/contributing/introduction-to-contributing/) to learn how to assign yourself

Yeah sure, thanks @BekahHW

**Comment by Suraj-kumar00** [comment] 2024-01-12 05:34
.take

**Comment by Suraj-kumar00** [comment] 2024-01-15 16:11
Hi @BekahHW, actually I'm getting the error after running the command `npm run`.
``` javascript
npm test
npm info using npm@10.2.3
npm info using node@v18.19.0
npm ERR! Missing script: "test" // this is the error I'm encountering 
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\offic\AppData\Local\npm-cache\_logs\2024-01-15T15_47_34_579Z-debug-0.log
```

there is no test file in package.json .
Please help me in this so I can complete this issue as soon as possible.

**Comment by BekahHW** [comment] 2024-01-18 18:21
@Suraj-kumar00 did you follow the instructions for running in the readme?

```
npm ci
npm start
```

**Comment by Suraj-kumar00** [comment] 2024-01-19 07:55
Yes sure I did @BekahHW 
After cloning, in the terminal, I first run
`npm run`
But actually, the problem is in this project the React 17 version is installed and I have installed the first React 21 version, and now React 18 version
I'm trying hard from Googling and AI to resolve this error but I'm getting nowhere!!!

**Comment by BekahHW** [comment] 2024-01-19 15:05
After cloning in the terminal, you should start with `npm ci`.

**Comment by Suraj-kumar00** [comment] 2024-01-19 15:09
> After cloning in the terminal, you should start with `npm ci`.

Yeah actually I did all things again and than it's working in local host, tomorrow I'll create pull request.

**Closed** 2024-01-26 21:30 UTC
Labels: good first issue
